protected/models/Category.php
<?php

/**
 * This is the model class for table "{{test_category}}".
 *
 * The followings are the available columns in table '{{test_category}}':
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $full_description
 * @property string $seo_title
 * @property string $seo_description
 * @property string $seo_keywords
 * @property string $base_code
 *
 * The followings are the available model relations:
 * @property Disk[] $disks
 * @property PayedGroup[] $payedGroups
 */
class Category extends CActiveRecordTimed
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Category the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return boolean If the category available for the current user (he's bought it)
	 */
	public function isAvailableForUser() {
		$allFree = Yii::app()->params['allCategoriesOpened'] === true;
		return count($this->payedGroups) != 0 || $allFree;
	}
	
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{test_category}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
			array('name, base_code, seo_title, seo_keywords', 'length', 'max'=>255),
			array('description, base_code, seo_title, seo_description, full_description, seo_keywords', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, description, full_description, seo_title, seo_description, seo_keywords', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @param mixed  $pk
	 * @param string $condition
	 * @param array  $params
	 *
	 * @return Category
	 */
	public function findByPk($pk, $condition = '', $params = array())
	{
		return parent::findByPk($pk, $condition, $params);
	}


	/**
	 * @return Category
	 */
	public function with()
	{
		return parent::with();
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'disks' => array(self::HAS_MANY, 'Disk', 'test_group_id'),
			'payedGroups' => array(self::HAS_MANY, 'PayedGroup', 'test_category_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Название',
			'description' => 'Описание',
			'base_code' => 'Код 1С',
			'full_description' => 'Подробное описание (под списком тестов)',
			'seo_title' => 'Meta Title SEO',
			'seo_description' => 'Meta Description SEO',
			'seo_keywords' => 'Meta Keywords',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('seo_title',$this->description,true);
		$criteria->compare('seo_description',$this->description,true);
		$criteria->compare('full_description',$this->description,true);
		$criteria->compare('seo_keywords',$this->description,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/CategoryController.php
<?php

/**
 *
 */
class CategoryController extends BaseController
{
    protected $MAX_DISKS_UNPAID = 1;

    public function filters()
    {
        $arr = array(
            array(
                'COutputCacheCustom + index',
                'duration' => 1000,
                'dependency' => array(
                    'class' => 'CDbCacheDependency',
                    'sql' => "SELECT MAX(`update_time`) FROM {{test_category}}",
                )
            ),
        );
        return $arr;
    }

    public function actionIndex()
    {
        $categories = Category::model()->with('payedGroups')->findAll();
        $this->render(
            'index',
            array(
                'categories' => $categories
            )
        );
    }

    /**
     * @param $id int
     */
    public function actionView($id, $all = null)
    {
//		$category = Category::model()->with('disks')->findByPk($id);
//		$disks = $category->disks;
//		$isAvailableForUser = $category->isAvailableForUser();
//		if (!$isAvailableForUser) {
//			foreach ($disks as $key=> $disk) {
//				if (!$disk->is_free) {
//					unset($disks[$key]);
//				}
//			}
//
//		}
        $category = Category::model()->cache(CACHE_TIME)->findByPk($id);
        // Turned off to make one less query on the page. It's not used now anyway
        //$isAvailableForUser = $category->isAvailableForUser();
        $isAvailableForUser = true;

        $criteria = new CDbCriteria();
        $criteria->compare("test_group_id", $category->id);
        $criteria->alias = 'tg';
        $criteria->order = 'tg.base_code DESC';
        if (!$isAvailableForUser) {
            $criteria->compare("is_free", true);
        }

        $disksDataProvider = new CActiveDataProvider(
            'Disk',
            array(
                'criteria' => $criteria,
                'pagination' => array(
                    'pageSize' => 5,
                ),
            )
        );

        $pages = null;
        if (empty($all)) {
            $count = Disk::model()->cache(CACHE_TIME)->count($criteria);

            $pages = new CPagination($count);
            $pages->pageSize = Yii::app()->params['pageSizes']['diskList'];
            $pages->applyLimit($criteria);
        }

        $disks = Disk::model()->cache(CACHE_TIME)->with('questions')->findAll($criteria);

//		if ($isAvailableForUser) {
//			$disks = array_slice($disks, 0, $this->MAX_DISKS_UNPAID);
//		}
        $this->render(
            'view',
            array(
                'disks' => $disks,
                'fullAccess' => $isAvailableForUser,
                'category' => $category,
                'pages' => $pages,
                //				 'disksDataProvider' => $disksDataProvider
            )
        );
    }

    // Uncomment the following methods and override them if needed
    /*
    public function filters()
    {
        // return the filter configuration for this controller, e.g.:
        return array(
            'inlineFilterName',
            array(
                'class'=>'path.to.FilterClass',
                'propertyName'=>'propertyValue',
            ),
        );
    }

    public function actions()
    {
        // return external action classes, e.g.:
        return array(
            'action1'=>'path.to.ActionClass',
            'action2'=>array(
                'class'=>'path.to.AnotherActionClass',
                'propertyName'=>'propertyValue',
            ),
        );
    }
    */
}

protected/controllers/TestController.php
<?php

class TestController extends AuthUserController
{
	protected $unAuthedActions = array(
		'index',
	);

	/**
	 * @param $did int Id of the disk to be tested with
	 */
	public function actionIndex($did)
	{
		$disk = $this->getFilterDiskAvailable($did);
		$this->render(
			'index',
			array(
				 'disk' => $disk,
			)
		);
	}

    /**
     * @param int $did Id of the disk
     * @param int $qid Number of the question on the disk
     * @param int $cid Category id
     * @throws CHttpException
     */
	public function actionQuestion($did, $qid = null, $cid = null)
	{
        if($qid === null) {
            $this->redirect(array('test/question','did' => $did, 'cid' => $cid, 'qid' => 1));
        }
		$disk = $this->getFilterDiskAvailable($did);
		$question = $disk->getQuestionByNumber($qid);
        if ($question == null) {
            throw new CHttpException("404", "Вопрос не найден.");
        }
        $attempt = UserAttempt::getCreateAttemptByDisk($disk);
        $this->writeAnswer($disk, $attempt);
		$questions = array();
        $answersDb = UserAnswer::model()->with('answer')->findAllByAttributes(array('attempt_id' => $attempt->id));
        $answers = array();
        foreach($answersDb as $curAnswer) {
            $answers[$curAnswer->question_id] = $curAnswer;
        }
		foreach ($disk->questions as $cur) {
			/*$answer = UserAnswer::model()->findByAttributes(
				array('question_id' => $cur->id, 'attempt_id' => $attempt->id)
			);*/
            $answer = array_key_exists($cur->id, $answers) ? $answers[$cur->id] : null;
			$questions[] = array(
				'question' => $cur,
				'answer'   => $answer,
			);
		}
//		if ($question != null) {
		$this->render(
			'question',
			array(
				 'question'      => $question,
				 'disk'          => $disk,
				 'qNumber'       => $qid,
				 'attempt'       => $attempt,
				 'questions'     => $questions,
			)
		);
//		} else {
//			$this->redirect(array("test/finish"));
//		}
	}

    /**
     * Shows a question in a view mode
     * @param $did Disk id
     * @param $qid Question id
     * @param null $aid Attempt id to return to the results view
     */
    public function actionView($did, $qid, $aid = null, $cid = null, $qans = null) {
        $disk = $this->getFilterDiskAvailable($did);
        $question = $disk->getQuestionByNumber($qid);
        if ($question == null) {
            throw new CHttpException("404", "Вопрос не найден.");
        }
        $this->render(
            'view',
            array(
                'question' => $question,
                'disk' => $disk,
                'qNumber' => $qid,
                'attemptId' => $aid,
                'userAnswer' => $qans,
            )
        );
    }

	private function writeAnswer(Disk $disk, UserAttempt $attempt)
	{
		if (isset($_POST["UserAnswer"])) {
			$userAnswerPost = $_POST["UserAnswer"];
//			var_dump($userAnswerPost);
			$userAnswer = new UserAnswer();
//			$userAnswer->attributes = $userAnswerPost;
			$answerId = $userAnswerPost["answer_id"];
			if (!isset($answerId) || $answerId === "") {
				// leave the question unanswered
				return;
			}
			$answer = Answer::model()->cache(CACHE_TIME)->findByPk($answerId);
			if ($answer == null) {
				throw new CHttpException("404", "Извините, вариант ответа не найден.");
			}
			if ($disk->id != $answer->question->disk->id) {
				throw new CHttpException("404", "Извините, ответ на вопрос не из запрошенного теста.");
			}
			$existingAnswer = UserAnswer::model()->findByAttributes(
				array(
					 'attempt_id'  => $attempt->id,
					 'question_id' => $answer->question_id,
				)
			);
			if ($existingAnswer != null) {
				$userAnswer = $existingAnswer;
			} else {
				$userAnswer->question_id = $answer->question_id;
				$userAnswer->attempt_id = $attempt->id;
			}
			$userAnswer->answer_id = $answerId;
            $userAnswer->correct = $answer->correct;
			$userAnswer->save(false);
//			list($question, $qid) = $disk->getNextQuestion($question);
		}
	}

	public function actionFinish($did, $cid = null)
	{
		$disk = $this->getFilterDiskAvailable($did);
		if(null == $cid) {
			$cid = $disk->category->id;
		}
		$attempt = UserAttempt::getActiveAttemptByDisk($disk);
		if ($attempt == null) {
			//throw new CHttpException("Нет активных попыток прохождения теста, чтобы его завершить.");
			$this->redirect(Yii::app()->createUrl('test/result',array('did'=>$did, 'cid'=>$cid)));
		}
		$this->writeAnswer($disk, $attempt);
		$attempt->finishAttempt();
		$this->render(
			'details',
			array(
				 'disk'    => $disk,
				 'attempt' => $attempt,
				 'finish'  => true,
			)
		);
	}

	public function actionResult($did, $cid = null)
	{
		$disk = $this->getFilterDiskAvailable($did);
		$attempts = UserAttempt::model()->getAllAttemptsByDisk($disk);
		$this->render(
			'result',
			array(
				 'disk'     => $disk,
				 'attempts' => $attempts,
			)
		);
	}

	public function actionDetails($id, $did = null, $cid = null) {
		$attempt = UserAttempt::model()->findByPk($id);
        $disk = $this->getFilterDiskAvailable($did);
		if($attempt == null) {
			if(null !== $did) {
				//$this->redirect(Yii::app()->createUrl('test/result', array('did'=>$did, 'cid'=>$cid)));
                $this->render(
                    'attempt_denied',
                    array(
                         'disk' => $disk
                    )
                );
                return;
            } else {
				$this->redirect('/');
            }
		}
		$this->render(
			'details',
			array(
				 'attempt' => $attempt,
                 'disk' => $disk,
			)
		);
	}

	/**
	 * @param $diskid int Id of disk to check
     * @return Disk
	 */
	private function getFilterDiskAvailable($diskid)
	{
       // $dependency = new CExpressionDependency('Yii::app()->user->id');
        $dependency = new CDbCacheDependency("SELECT MAX(`update_time`) FROM {{question}} WHERE `disk_id`=:disk");
        $dependency->params = array(':disk' => $diskid);
		$disk = Disk::model()->cache(CACHE_TIME, $dependency)->with(array("category", /*'category.payedGroups', */'questions'=>array('alias'=>'q'),
            'questions.answers'=>array('alias'=>'z', 'order'=>'q.id, ifnull(z.order, 0) ASC, z.id ASC')))->findByPk($diskid);
		if ($disk == null) {
			throw new CHttpException("404", "Диск не найден.");
		}
        // Won't need it in the future, just some performance tuning
		/*if (!$disk->is_free && !$disk->category->isAvailableForUser()) {
			$this->redirect(array("payment/buy", "id" => $disk->category->id));
		}*/
		return $disk;
	}

	// Uncomment the following methods and override them if needed
	/*
public function filters()
{
	// return the filter configuration for this controller, e.g.:
	return array(
		'inlineFilterName',
		array(
			'class'=>'path.to.FilterClass',
			'propertyName'=>'propertyValue',
		),
	);
}

public function actions()
{
	// return external action classes, e.g.:
	return array(
		'action1'=>'path.to.ActionClass',
		'action2'=>array(
			'class'=>'path.to.AnotherActionClass',
			'propertyName'=>'propertyValue',
		),
	);
}
*/
}

protected/views/category/index.php
<?php
/* @var $this CategoryController */
/* @var $categories array */

$this->breadcrumbs = array(
);
$this->pageTitle = "Тесты 1С:Профессионал - онлайн подготовка";
Yii::app()->clientScript->registerMetaTag('Онлайн подготовка к тестированию 1С:Профессионал по платформе, бухгалетрии, управлению торговленй и другим конфигурациям.', 'description');
?>
<h1>Тесты 1С Профессионал - онлайн подготовка</h1>

<?php $this->widget('ShareButtonsWidget'); ?>

<?php if(count($categories) === 0) : ?>
    <p class="empty-list">
        Что-то ничего не загрузили еще...
    </p>
<?php else : ?>
<ul id="category-list">
	<?php foreach ($categories as $category) : ?>
	<?php
    /* @var $category Category */
    $isAvailableForUser = $category->isAvailableForUser();
    ?>
	<li class="category-line<?php if(!$isAvailableForUser) echo " closed"; ?>">
		<a href="<?php echo CHtml::normalizeUrl(array('category/view', 'id'=> $category->id)); ?>">
		<h2 class="category-link">
		<?php echo $category->name; ?>
		<?php if(!$isAvailableForUser) echo "Закрыт"; ?>
		</h2>
<!--        <div class="well">-->
		    <span class="category-description"><?php echo $category->description; ?></span>
<!--        </div>-->
			</a>
	</li>
	<?php endforeach ?>
</ul>


<div id="categories-seo">
<h2>1С тесты онлайн</h2>
<p>В каждой категории собрано большое количество тестов по 1С для подготовки к тестированию 1С:Профессионал. Тесты 1С представляют собой группы по 14 закрытых вопросов, то есть таких, на которые нужно выбрать один ответ из нескольких предложенных вариантов. Тест 1С считается пройденным, если дано не менее 12 правильных ответов.</p>
<p>1С разделяет тесты на несколько групп по областям знаний. На данный момент на сервисе онлайн подготовки к тестам 1С представлены наиболее популярные группы, получение сертфиката по которым дает много преимуществ для Вас. Успешная сдача тестов 1С по платформе, например, позволит Вам подтвердить свои знания основ платформы и откроет двери для сдачи экзамена 1С:Специалист. Тесты 1С по Бухгалтерии предприятия очень полезны для бухгалтера.</p>
</div>
<?php endif; ?>

<?php
Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . "/css/category.css");
Yii::app()->clientScript->registerCssFile(Yii::app()->theme->baseUrl . "/css/category.css");
?>

protected/views/category/view.php
<?php
/* @var $this CategoryController */
/* @var $category Category */
/* @var $disks array */
/* @var $disksDataProvider CActiveDataProvider */
/* @var $fullAccess boolean */
/* @var $pages CPagination */

$this->breadcrumbs = array(
    'Тесты 1С' => array('category/index'),
    $category->name,
);

$meta_title = $category->seo_title;
if (empty($meta_title)) $meta_title = $category->name;
$full_desc = $category->full_description;
if (empty($full_desc)) $full_desc = $category->description;
$meta_desc = $category->seo_description;
if (empty($meta_desc)) $meta_desc = $category->name . ' для подготовки к тестированию 1С:Профессионал';
$meta_keys = $category->seo_keywords;

Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl . '/css/category-view.css');
Yii::app()->clientScript->registerCssFile(Yii::app()->theme->baseUrl . '/css/category-view.css');
$this->pageTitle = $meta_title . " - Онлайн подготовка к тестированию 1С:Профессионал";
Yii::app()->clientScript->registerMetaTag($meta_desc, 'description');
if (!empty($meta_keys))
    Yii::app()->clientScript->registerMetaTag($meta_keys, 'keywords');
if (!empty($pages)) {
    Yii::app()->clientScript->registerLinkTag(
        'canonical',
        null,
        CHtml::normalizeUrl(Array('category/view', 'id' => $category->id, 'all' => 1))
    );
}
?>
<h1>Список тестов раздела "<?php echo $category->name; ?>"</h1>

<?php $this->widget('ShareButtonsWidget'); ?>

<?php if(Yii::app()->getModule("user")->isAdmin()) : ?>
    <div class="admin-action"><?php echo CHtml::link('Редактировать раздел', array('categoryAdmin/update', 'id'=>$category->id)); ?></div>
<?php endif; ?>

<ul id="disks-list">
    <?php
    $disksIds = array();
    foreach($disks as $disk) {
        $disksIds[] = $disk->id;
    }
    $correctCounts = UserAttempt::getCorrectAnswersCountByDiskArray($disksIds);
    foreach ($disks as $disk) : ?>
    <?php /* @var $disk Disk */

    //$correct = UserAttempt::getCorrectAnswersCountByDisk($disk);
    $correct = array_key_exists($disk->id, $correctCounts) ? $correctCounts[$disk->id] : 0;
    $total = $disk->getQuestionCount();
    $completed = $correct === $total; ?>
    <li<?php if ($completed) echo ' class="completed"'; ?>><?php echo CHtml::link($disk->name, array("test/index", "cid" => $category->id, "did" => $disk->id)) ?>
        <?php
        if (!Yii::app()->user->isGuest) : ?>
        <p><?php echo $correct;  ?>/<?php echo $total; ?></p>
        <?php endif; ?></li>
    <?php endforeach ?>
</ul>

<?php if (!empty($pages)) $this->widget('CLinkPager', array('pages' => $pages)); ?>
<div class="page-switcher">
    <?php if (!empty($pages)) {
    echo CHtml::link("Все тесты раздела", array('category/view', 'id' => $category->id, 'all' => 1));
} else {
    echo CHtml::link("По страницам", array('category/view', 'id' => $category->id));
}?>
</div>
<?php if (!$fullAccess) : ?>
<div class="more-disks"><?php echo CHtml::link(
    "Пройти остальные тесты", array("payment/buy", "id" => $category->id)
) ?></div>
<?php endif ?>
<div class="full-description">
    <?php echo $full_desc; ?>
</div>